language: node_js

node_js:
  - 8.9.1
  - 12

before_install:
  - export TZ=Canada/Eastern
  - npm install -g grunt-cli

install:
  - yarn

script: grunt deploy

after_success:
  - touch "dist/deployed at `date`"
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_REPO_SLUG}" = "FieldDB/dative" ]  && ncftpput -R -v -u $USERNAME -p $PASSWORD $SERVER /beta dist/*'
